version: '3'
services:
  jupyter:
    build: 
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - "8888:8888"
      - "21:21"
      - "60822:22"
    command: "start-notebook.sh --NotebookApp.token="
    environment:
      - PASSWORD=password
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  remote-desktop:
    build:
      context: .
      dockerfile: ./docker/remote-desktop/Dockerfile
    container_name: remote-desktop
    privileged: true
    ports:
      - "3389:3389"  # RDP port
      - "2222:22"    # SSH port
    volumes:
      - ./work:/home/user/work:rw
    environment:
      - DISPLAY=:0
      - USER=user
      - PASSWORD=Cwit2016
      - TZ=Asia/Singapore
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: '2gb'
    restart: unless-stopped

  frpc:
    build:
      context: .
      dockerfile: ./docker/frpc/Dockerfile
    container_name: frpc
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/frpc.toml:/etc/frp/frpc.toml:ro
      - ./logs:/frp/logs
    environment:
      - N_USER=fyp_2022
      - VPN_PASSWORD=Cwit2022!@#
      - SERVERCERT=pin-sha256:Pnb4NQY/oONvNeSgMn6P8neFR1h61IjA2mR+9cxvefg=
