version: '3'
services:
  jupyter:
    build: 
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - "8888:8888"
      - "21:21"
      - "60822:22"
    command: "start-notebook.sh --NotebookApp.token=${JUPYTER_TOKEN} --NotebookApp.password=${JUPYTER_PASSWORD} --NotebookApp.ip='0.0.0.0'"
    environment:
      - PASSWORD=${REMOTE_DESKTOP_PASSWORD}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all,compute,utility
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]

  remote-desktop:
    build:
      context: .
      dockerfile: ./docker/remote-desktop/Dockerfile
    container_name: remote-desktop
    privileged: true
    ports:
      - "3389:3389"  # RDP port
      - "2222:22"    # SSH port
    volumes:
      - ./work:/home/user/work:rw
    environment:
      - DISPLAY=:0
      - USER=${REMOTE_DESKTOP_USER}
      - PASSWORD=${REMOTE_DESKTOP_PASSWORD}
      - TZ=Asia/Singapore
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: '2gb'
    restart: unless-stopped

  frpc:
    build:
      context: .
      dockerfile: ./docker/frpc/Dockerfile
    container_name: frpc
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/frpc.toml:/etc/frp/frpc.toml:ro
      - ./logs:/frp/logs
    environment:
      - N_USER=${VPN_USER}
      - VPN_PASSWORD=${VPN_PASSWORD}
      - SERVERCERT=${VPN_SERVERCERT}
