version: '3'
services:
  jupyter:
    build: 
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
      - 21:21
      - 60822:22
    command: "start-notebook.sh --NotebookApp.token="
    environment:
      - PASSWORD=password
  frpc:
    image: snowdreamtech/frpc:0.52.3
    container_name: frpc
    restart: always
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/frpc.toml:/etc/frp/frpc.toml:ro
      - ./logs:/frp/logs
